version: 3.9

services:
  api:
    restart: always
    image: openfoodfacts/robotoff:${TAG}
    network_mode: "host"
    volumes:
      - api-dataset:/opt/robotoff/datasets
      - /home/robotoff/tf_models:/opt/robotoff/tf_models
      - /home/robotoff/models:/opt/robotoff/models
    mem_limit: 2g

  workers:
    restart: always
    image: openfoodfacts/robotoff:dev
    network_mode: "host"
    volumes:
      - api-dataset:/opt/robotoff/datasets
      - ./tf_models:/opt/robotoff/tf_models:Z
      - ./models:/opt/robotoff/models:Z
    entrypoint: "/root/.local/bin/poetry run robotoff-cli run workers"
    mem_limit: 8g

  scheduler:
    restart: always
    image: openfoodfacts/robotoff:dev
    network_mode: "host"
    volumes:
      - api-dataset:/opt/robotoff/datasets
      - ./tf_models:/opt/robotoff/tf_models:Z
      - ./models:/opt/robotoff/models:Z
    entrypoint: "/root/.local/bin/poetry run robotoff-cli run scheduler"
    mem_limit: 4g

  postgres:
    restart: always
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD
    volumes:
    - postgres-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    command: postgres -c shared_buffers=1024MB -c work_mem=64MB
    mem_limit: 4g
    shm_size: 1g

  elasticsearch:
    restart: always
    image: raphael0202/elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    mem_limit: 1500m
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"

  tf_serving:
    restart: always
    image: tensorflow/serving:1.15.0
    ports:
      - "127.0.0.1:8501:8501"
      - "127.0.0.1:8500:8500"
    volumes:
      - /home/robotoff/tf_models:/models
    entrypoint: "tensorflow_model_server --port=8500 --rest_api_port=8501 --model_config_file=/models/models.config"
    mem_limit: 10g

volumes:
  postgres-data:
    external: true

  api-dataset:
    external: true

  es-data:
    external: true
