version: "3.9"
services:
  api:
    command:
      - gunicorn
      - --config /opt/robotoff/gunicorn.py
      - --statsd-host=statsd:9125
      - --statsd-prefix=robotoff
      - --log-file=-
      - robotoff.app.api:api
    depends_on:
      - statsd
  statsd:
    image: prom/statsd-exporter
    volumes:
      - ./statsd.conf:/statsd/statsd.conf
    command:
      - "--statsd.mapping-config=/statsd/statsd.conf"
    ports:
      - 9102:9102
    networks:
      - webnet
