name: Sync ML models to Proxmox VM
on:
  push:
    tags:
      - model-deploy-net*
      - model-deploy-org*

jobs:
  ml-models-sync:
    name: Sync ML models
    runs-on: ubuntu-latest
    environment: ${{ matrix.env }}
    concurrency: ${{ matrix.env }}-${{ matrix.asset_name }}
    strategy:
      matrix:
        asset_name:
          - tf-universal-logo-detector
          - tf-nutrition-table
          - tf-nutriscore
        env:
          - ${{ startsWith(github.ref, 'refs/tags/model-deploy-org') && 'robotoff-ml-org' || 'robotoff-ml-net' }}
          # Syncing to robotoff-net/org is required as post-processing for most models is done
          # on the caller side, i.e. the caller needs access to the label_map.pbtxt file.
          - ${{ startsWith(github.ref, 'refs/tags/model-deploy-org') && 'robotoff-org' || 'robotoff-net' }}
    steps:
      - name: Set common variables
        run: |
          echo "SSH_PROXY_HOST=ovh2.openfoodfacts.org" >> $GITHUB_ENV
          echo "SSH_USERNAME=off" >> $GITHUB_ENV
      - name: Set various variables for 'robotoff-ml-net' environment
        if: matrix.env == 'robotoff-ml-net'
        run: |
          echo "PROJECT_DIR=robotoff-ml" >> $GITHUB_ENV
          echo "SSH_HOST=10.1.0.200" >> $GITHUB_ENV
      - name: Set various variables for 'robotoff-ml-org' environment
        if: matrix.env == 'robotoff-ml-org'
        run: |
          echo "PROJECT_DIR=robotoff-ml" >> $GITHUB_ENV
          echo "SSH_HOST=10.1.0.201" >> $GITHUB_ENV
      - name: Set various variables for 'robotoff-net' environment
        if: matrix.env == 'robotoff-net'
        run: |
          echo "PROJECT_DIR=robotoff-net" >> $GITHUB_ENV
          echo "SSH_HOST=10.1.0.200" >> $GITHUB_ENV
      - name: Set various variables for 'robotoff-org' environment
        if: matrix.env == 'robotoff-org'
        run: |
          echo "PROJECT_DIR=robotoff-org" >> $GITHUB_ENV
          echo "SSH_HOST=10.1.0.201" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Download
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{ env.SSH_PROXY_HOST }}
          proxy_username: ${{ env.SSH_USERNAME }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.PROJECT_DIR }}/models
            dir=`echo ${{ matrix.asset_name }} | sed 's/tf-//g'`
            mkdir -p ${dir} ${dir}/1
            wget -cO - https://github.com/openfoodfacts/robotoff-models/releases/download/${{ matrix.asset_name }}-1.0/labels.txt > ${dir}/labels.txt

            if [ ${{ env.PROJECT_DIR }} = 'robotoff-ml' ]; then
              wget -cO - https://github.com/openfoodfacts/robotoff-models/releases/download/${{ matrix.asset_name }}-1.0/model.onnx > ${dir}/1/model.onnx
            fi

  # The category classifier has the pre- and post-processing built in, therefore
  # it requires a slightly different sequence of steps to the 'ml-models-sync' above.
  tfmodels-category-classifier-sync:
    name: Sync Category Classifier
    runs-on: ubuntu-latest
    environment: ${{ matrix.env }}
    concurrency: ${{ matrix.env }}-${{ matrix.asset_name }}
    strategy:
      matrix:
        asset_name:
          - tf-category-classifier
        env:
          - ${{ startsWith(github.ref, 'refs/tags/model-deploy-org') && 'robotoff-ml-org' || 'robotoff-ml-net' }}
    steps:
      - name: Set common variables
        run: |
          echo "SSH_PROXY_HOST=ovh2.openfoodfacts.org" >> $GITHUB_ENV
          echo "SSH_USERNAME=off" >> $GITHUB_ENV
      - name: Set various variable for staging deployment
        if: matrix.env == 'robotoff-ml-net'
        run: |
          echo "SSH_HOST=10.1.0.200" >> $GITHUB_ENV
      - name: Set various variable for production deployment
        if: matrix.env == 'robotoff-ml-org'
        run: |
          echo "SSH_HOST=10.1.0.201" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Download
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_host: ${{ env.SSH_PROXY_HOST }}
          proxy_username: ${{ env.SSH_USERNAME }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd robotoff-ml/tf_models
            dir=`echo ${{ matrix.asset_name }} | sed 's/tf-//g'`
            mkdir -p ${dir} ${dir}/1
            wget -cO - https://github.com/openfoodfacts/robotoff-models/releases/download/keras-category-classifier-xx-2.0/serving_model.tar.gz > ${dir}/1/saved_model.tar.gz
            cd ${dir}/1
            tar -xzvf saved_model.tar.gz --strip-component=1
            rm saved_model.tar.gz
